version: '3'

volumes:
  LAMPhp73:

services:
  LAMPhp73_web:
    image: rstriquer/LAMPhp73:3.0
    container_name: LAMPhp73_web
    volumes:
      - ./public_html:/var/www/html
      - ./docker/php.ini:/etc/php/7.3/apache2/conf.d/99-docker.ini
      - ./docker/apache-000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/apache-000-default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
      - ./docker/ssl.crt:/etc/apache2/ssl/ssl.crt
      - ./docker/ssl.key:/etc/apache2/ssl/ssl.key
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - LAMPhp73_db

  LAMPhp73_db:
    image: mysql:5.6
    container_name: LAMPhp73_db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - LAMPhp73:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123qwe
